routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Front\ContentController;
use App\Http\Controllers\Admin\PageController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\PostController;
use App\Http\Controllers\Admin\PermissionController;
use App\Http\Controllers\Admin\HomeController;
use App\Http\Controllers\Admin\NewsletterController;

use App\Http\Controllers\MailChimpController;

use App\Http\Controllers\ApiController;

use App\Http\Livewire\Dashboard;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

//Redactor Image Upload
Route::post('/upload/images', [ApiController::class, 'upload']);
Route::get('/images/feed', [ApiController::class, 'imagefeed']);



//Redactor File Upload
// Route::post('upload/files', 'ApiController@fileupload');
// Route::get('file/feed', 'ApiController@filefeed');



Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => ['auth:sanctum', 'verified']], function () {

    

    Route::get('/', [HomeController::class, 'index'])->name('home');

    // Pages
	Route::resource('pages', PageController::class, ['except' => ['destroy', 'show']]);
	Route::get('snippets', [PageController::class, 'snippets'])->name('snippets');


	// Permissions
    Route::resource('permissions', PermissionController::class, ['except' => ['store', 'update', 'destroy']]);

    // Roles
    Route::resource('roles', RoleController::class, ['except' => ['store', 'update', 'destroy']]);

    // Users
    Route::resource('users', UserController::class, ['except' => ['store', 'update', 'destroy']]);

    Route::resource('posts', PostController::class, ['except' => ['destroy', 'show']]);

    // Newsletters
    Route::resource('newsletters', NewsletterController::class);
    Route::get('newsletters/{id}/test', [NewsletterController::class, 'gettest'])->name('emailtest');
    Route::post('newsletters/{id}/test', [NewsletterController::class, 'sendtest']);
    Route::get('newsletters/{id}/send', [NewsletterController::class, 'send'])->name('emailsend');

    Route::get('emailsnippets', [NewsletterController::class, 'emailsnippets'])->name('emailsnippets');

});

// Route::middleware(['auth:sanctum', 'verified'])->get('/admin', function () {
//     return view('dashboard');
// })->name('admin');
Route::get('/send-mail-using-mailchimp', [MailChimpController::class, 'index'])->name('send.mail.using.mailchimp.index');



//Posts
Route::get('/posts', [ContentController::class, 'posts'])->name('posts');
Route::get('/posts/{id}', [ContentController::class, 'post'])->name('post');
Route::get('/posts/category/{id}', [ContentController::class, 'category'])->name('category');


// Users
Route::resource('users', UserController::class);

// API
Route::get('/api/meetup', [ContentController::class, 'api_meetup'])->name('api_meetup');
Route::get('/api/posts', [ContentController::class, 'api_posts'])->name('api_posts');


Route::get('/test', function() {
  return File::get(public_path() . '/classy-mailchimp.html');
});

// Home

Route::resource('/signup', MailChimpController::class);
Route::get('/signup/{id}/remove', [MailChimpController::class, 'remove'])->name('remove');


Route::name('home')->get('/', [ContentController::class, 'index'])->name('index');
Route::get('/home', [ContentController::class, 'index'])->name('index');
Route::get('/{page}', [ContentController::class, 'page'])->name('page');

app/Http/Controllers/Front/ContentController.php
<?php

namespace App\Http\Controllers\Front;

use App\Http\Controllers\Controller;
use App\Http\Requests;
use App\Models\Page;
use App\Models\Post;
use App\Models\Category;
use Illuminate\Http\Request;
use App\Services\MeetupService;
use DB;


// use Spatie\Searchable\Search;

class ContentController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $content = Page::where('id', 1)->first();
        $active = '';

        $pages = Page::all();

        return view('front.pages.page', compact('content', 'active'));
        // return view('front.pages.test', compact('content', 'active'));
    }

    public function signup()
    {

        return view('front.pages.signup');
        // return view('front.pages.test', compact('content', 'active'));
    }

    public function page($page)
    {

        // $frontmenu = Page::where('parent_id', null)->get();
        $content = Page::where('slug', $page)->first();
        $active = $page;

        if ($content->parent_id != null) {
            $active = $content->parent->slug;
        }

        return view('front.pages.page', compact('content', 'active'));
    }

    public function api_meetup(MeetupService $meetupservice)
    {
        $json = $meetupservice->events();

        $events = json_decode($meetupservice->events());

        $events = array_slice($events, 0, 6);

        return $events;
        // return view('front.pages.test', compact('content', 'active'));
    }

    public function api_posts()
    {
    
        $posts = Post::with('user')
            ->select('id', 'title', 'slug', 'user_id', 'image', 'readtime')
            ->addSelect(DB::raw("DATE_FORMAT(published, '%D %M %Y') AS display_date"))
            ->orderBy('published', 'DESC')->where('published', '!=', '')->where('active', '1')
            ->take(3)
            ->get();

        return $posts;
       
    }

    public function posts()
    {
        $featured = Post::where('featured', 1)->first();

        $posts = Post::with('user')
            ->select('id', 'title', 'slug', 'summary', 'user_id', 'image', 'readtime', 'featured','published')
            ->addSelect(DB::raw("DATE_FORMAT(published, '%D %M %Y') AS display_date"))
            ->where('featured', '!=', 1)
            ->orderBy('published', 'DESC')->where('published', '!=', '')->where('active', '1')
            ->get();

        $newposts = Post::with('user')
            ->select('id', 'title', 'slug', 'summary', 'user_id', 'image', 'readtime', 'featured','published')
            ->addSelect(DB::raw("DATE_FORMAT(published, '%D %M %Y') AS display_date"))
            ->orderBy('published', 'DESC')->where('published', '!=', '')->where('active', '1')
            ->take(5)
            ->get();

        $categories = Category::orderBy('title', 'asc')->whereHas('posts')->get();

        $active = 'post';

        return view('front.posts.index', compact('featured', 'posts', 'categories', 'active', 'newposts'));
        // return view('front.pages.test', compact('content', 'active'));
    }

    public function category($id)
    {
        $posts = Post::
            whereHas('category', function ($query) use ($id) {
                return $query->where('slug', $id);
            })
            ->select('id', 'title', 'slug', 'summary', 'user_id', 'image', 'readtime', 'published', 'category_id')
            ->addSelect(DB::raw("DATE_FORMAT(published, '%D %M %Y') AS display_date"))
            ->orderBy('published', 'DESC')->where('published', '!=', '')->where('active', '1')
            ->with('user', 'category')
            ->get();

        $category = Category::where('slug', $id)->first();

        $active = 'post';

        return view('front.posts.category', compact('posts', 'category', 'active'));
        // return view('front.pages.test', compact('content', 'active'));
    }


    public function post($id)
    {
        $post = Post::
           where('slug', $id)
            ->select('id', 'title', 'slug', 'summary', 'content', 'user_id', 'image', 'readtime', 'published', 'category_id')
            ->addSelect(DB::raw("DATE_FORMAT(published, '%D %M %Y') AS display_date"))
            ->orderBy('published', 'DESC')->where('published', '!=', '')->where('active', '1')
            ->with('user', 'category')
            ->first();

        $active = 'post';

        return view('front.posts.post', compact('post', 'active'));
        // return view('front.pages.test', compact('content', 'active'));
    }
    
}

resources/views/front/pages/home.blade.php
@extends('layouts.home')

@section('content')
{!! $content->content !!}
@endsection 

resources/views/front/pages/page.blade.php
@extends('layouts.front')
@section('content')
{!! $content->content !!}
@endsection

resources/views/front/pages/signup.blade.php
@extends('layouts.front')
@section('content')

<div class="flex flex-wrap overflow-hidden md:-mx-5 lg:-mx-5 xl:-mx-5">

  <div class="w-full overflow-hidden md:my-1 md:px-1 md:w-1/3 lg:my-2 lg:px-2 lg:w-1/3 xl:my-2 xl:px-2 xl:w-1/3">
    <img class="object-cover object-center mr-10 " alt="hero" src="/assets/images/mail.png">
  </div>

  <div class="w-full overflow-hidden md:my-20 md:px-1 md:w-2/3 lg:my-10 lg:px-5 lg:w-2/3 xl:my-10 xl:px-5 xl:w-2/3 ">



    @if ($sent == 1)
    <div>
        <h2 class="text-4xl font-bold tracking-tight">Signup</h2>
        <div class="mt-5 bg-custom-100 p-3 rounded">
            <h3 class="text-xl font-bold tracking-tight ">Thanks for signing up! </h3>
            @if ($hasmember != 1)
            <div class="mt-2 mb-5">Please check your inbox to verify your email address. (It may be in your Spam folder.)</div>
            @endif
        </div>
    </div>
    @else
    <x-form.open method="POST" action="{{route('signup.store')}}" id="form">
        @method('POST')

    
        <h2 class="text-4xl font-bold tracking-tight">Signup</h2>

        <p class="mt-5">Use this form to signup for either our newsletter or membership (or both!)</p>

        <div class="flex flex-wrap overflow-hidden sm:-mx-1 md:-mx-1 lg:-mx-1 xl:-mx-1 mt-5">

          <div class="w-full overflow-hidden sm:my-1 sm:px-1 sm:w-1/2 md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-1 xl:px-1 xl:w-1/2">
            <label for="FNAME" class="block font-medium text-gray-500">First Name <span class="text-red-500">*</span></label>
            <input type="text" name="FNAME" id="mce-FNAME" value="" class="transition duration-200 border border-gray-300 bg-white text-gray-900 appearance-none sm:text-md sm:leading-5 rounded-sm py-2 px-2 focus:border-custom-400 focus:outline-none mb-4 mt-1 block w-full" required>          </div>

          <div class="w-full overflow-hidden sm:my-1 sm:px-1 sm:w-1/2 md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-1 xl:px-1 xl:w-1/2">
            <label for="LNAME" class="block font-medium text-gray-500">Last Name <span class="text-red-500">*</span></label>
            <input type="text" name="LNAME" id="mce-LNAME" value="" class="transition duration-200 border border-gray-300 bg-white text-gray-900 appearance-none sm:text-md sm:leading-5 rounded-sm py-2 px-2 focus:border-custom-400 focus:outline-none mb-4 mt-1 block w-full" required>
          </div>

        </div>


        <div class="mb-5">
            <label for="EMAIL" class="block font-medium text-gray-500">Email <span class="text-red-500">*</span></label>
            <input type="email" value="" name="EMAIL" id="mce-EMAIL" class="transition duration-200 border border-gray-300 bg-white text-gray-900 appearance-none sm:text-md sm:leading-5 rounded-sm py-2 px-2 focus:border-custom-400 focus:outline-none mb-4 mt-1 block w-full" required>
        </div>

     

        <div class="border border-gray-300 rounded p-4 mt-5">
            <h3 class="text-xl font-bold tracking-tight ">Newsletter</h3>
            <p class="mt-5">Receive regular updates, usually monthly, on our upcoming activities.</p>
            <div class="mt-3">
                <label for="active" class="inline-flex items-center">
                    <input type="checkbox" value="410d53c68d" name="interest1" id="interest1" class="form-checkbox h-5 w-5 text-custom-600 transition duration-150 ease-in-out mt-1 text-green-600">
                    <span class="ml-2 font-medium font-bold text-gray-700">Newsletter</span>
                </label>
            </div>
        </div>

        <div class="border border-gray-300 rounded p-4  mt-5">
            <h3 class="text-xl font-bold tracking-tight ">Membership </h3>
            <p class="mt-5">If you would like to be counted as a member of our group then please tick below.  There is no obligation to join and you will still be most welcome at any of our events.
                <BR><BR>
                The benefits of becoming a member are that we will keep you informed of any decisions that are made about how the group operates.  Membership will also allow you to participate in our AGM and influence how the group is run. You will receive one or two emails per year.
                <div class="my-3">
                    <label for="active" class="inline-flex items-center">
                        <input type="checkbox" value="c9fedc5641" name="interest2" id="interest2" class="form-checkbox h-5 w-5 text-custom-600 transition duration-150 ease-in-out mt-1 text-green-600">
                        <span class="ml-2 font-bold font-medium text-gray-700">I wish to be a member of Central London Humanists (no cost)</span>
                    </label>
                </div>
                <BR>
                <p class="">If you would like to vote at our AGM or become a committee member you will also need to be a member of <a href="https://humanism.org.uk/join/" target="_blank" class="text-custom-500">Humanists UK</a>.</p>
                <div class="my-3">
                    <label for="active" class="inline-flex items-center">
                        <input type="checkbox" value="c90bc770f9" name="interest3" id="interest3" class="form-checkbox h-5 w-5 text-custom-600 transition duration-150 ease-in-out mt-1 text-green-600">
                        <span class="ml-2 font-medium font-bold text-gray-700">I'm a member of Humanists UK</span>
                    </label>
                </div>
            </p>
        </div>

        <div class="border border-gray-300 rounded p-4 mt-5">
            <div class="content__gdpr">
                <p>You can unsubscribe or change your choices at any time by clicking the link in the footer of our emails.</p><BR>
            </div>
            <div class="text-sm">
                <p>We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. Learn more about Mailchimp's privacy practices <a href="https://mailchimp.com/legal/" target="_blank" class="text-custom-500">here.</a></p>
            </div>

            <input type="submit" value="Subscribe" name="subscribe" id="subscribe" class="mt-5 bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">


        </div>

    </x-form.open> 
    @endif
  </div>

</div>

@endsection

resources/views/front/pages/update.blade.php
@extends('layouts.front')
@section('content')

<div class="flex flex-wrap overflow-hidden md:-mx-5 lg:-mx-5 xl:-mx-5">

  <div class="w-full overflow-hidden md:my-1 md:px-1 md:w-1/3 lg:my-2 lg:px-2 lg:w-1/3 xl:my-2 xl:px-2 xl:w-1/3">
    <img class="object-cover object-center mr-10 " alt="hero" src="/assets/images/mail.png">
  </div>

  <div class="w-full overflow-hidden md:my-20 md:px-1 md:w-2/3 lg:my-10 lg:px-5 lg:w-2/3 xl:my-10 xl:px-5 xl:w-2/3 ">


    @if ($sent == 1)
    <div>
        <h2 class="text-4xl font-bold tracking-tight">Signup </h2>
        <div class="mt-5 bg-custom-100 p-3 rounded">
            <h3 class="text-xl font-bold tracking-tight ">Thanks for signing up! </h3>
            @if ($hasmember != 1)
            <div class="mt-2 mb-5">Please check your inbox to verify your email address. (It may be in your Spam folder.)</div>
            @endif
        </div>
    </div>
    @else
    <x-form.open method="POST" action="{{route('signup.store')}}" id="form">
        @method('POST')

    
        <h2 class="text-4xl font-bold tracking-tight">Update</h2>

        <p class="mt-5 mb-3">Hi {!! $member['merge_fields']['FNAME'] !!}</p>
        <p> Use this form to update your choices for either our newsletter or membership (or both!)</p>

        <div class="flex flex-wrap overflow-hidden sm:-mx-1 md:-mx-1 lg:-mx-1 xl:-mx-1 mt-5">

          <div class="w-full overflow-hidden sm:my-1 sm:px-1 sm:w-1/2 md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-1 xl:px-1 xl:w-1/2">
            <label for="FNAME" class="block font-medium text-gray-500">First Name <span class="text-red-500">*</span></label>
            <input type="text" name="FNAME" id="mce-FNAME" value="{!! $member['merge_fields']['FNAME'] !!}" class="transition duration-200 border border-gray-300 bg-white text-gray-900 appearance-none sm:text-md sm:leading-5 rounded-sm py-2 px-2 focus:border-custom-400 focus:outline-none mb-4 mt-1 block w-full" required>          </div>

          <div class="w-full overflow-hidden sm:my-1 sm:px-1 sm:w-1/2 md:my-1 md:px-1 md:w-1/2 lg:my-1 lg:px-1 lg:w-1/2 xl:my-1 xl:px-1 xl:w-1/2">
            <label for="LNAME" class="block font-medium text-gray-500">Last Name <span class="text-red-500">*</span></label>
            <input type="text" name="LNAME" id="mce-LNAME" value="{!! $member['merge_fields']['LNAME'] !!}" class="transition duration-200 border border-gray-300 bg-white text-gray-900 appearance-none sm:text-md sm:leading-5 rounded-sm py-2 px-2 focus:border-custom-400 focus:outline-none mb-4 mt-1 block w-full" required>
          </div>

        </div>


        <div class="mb-5">
            <label for="EMAIL" class="block font-medium text-gray-500">Email <span class="text-red-500">*</span></label>
            <input type="email" value="{!! $member['email_address'] !!}" name="EMAIL" id="mce-EMAIL" class="transition duration-200 border border-gray-300 bg-white text-gray-900 appearance-none sm:text-md sm:leading-5 rounded-sm py-2 px-2 focus:border-custom-400 focus:outline-none mb-4 mt-1 block w-full" required>
        </div>

     

        <div class="border border-gray-300 rounded p-4 mt-5">
            <h3 class="text-xl font-bold tracking-tight ">Newsletter</h3>
            <p class="mt-5">Receive regular updates, usually monthly, on our upcoming activities.</p>
            <div class="mt-3">
                <label for="active" class="inline-flex items-center">
                    <input type="checkbox" value="410d53c68d" name="interest1" id="interest1" class="form-checkbox h-5 w-5 text-custom-600 transition duration-150 ease-in-out mt-1 text-green-600" @if($member['interests']['410d53c68d'] == true) checked='checked' @endif>
                    <span class="ml-2 font-medium font-bold text-gray-700">Newsletter</span>
                </label>
            </div>
        </div>

        <div class="border border-gray-300 rounded p-4  mt-5">
            <h3 class="text-xl font-bold tracking-tight ">Membership </h3>
            <p class="mt-5">If you would like to be counted as a member of our group then please tick below.  There is no obligation to join and you will still be most welcome at any of our events.
                <BR><BR>
                The benefits of becoming a member are that we will keep you informed of any decisions that are made about how the group operates.  Membership will also allow you to participate in our AGM and influence how the group is run. You will receive one or two emails per year.
                <div class="my-3">
                    <label for="active" class="inline-flex items-center">
                        <input type="checkbox" value="c9fedc5641" name="interest2" id="interest2" class="form-checkbox h-5 w-5 text-custom-600 transition duration-150 ease-in-out mt-1 text-green-600" @if($member['interests']['c9fedc5641'] == true) checked='checked' @endif>
                        <span class="ml-2 font-bold font-medium text-gray-700">I wish to be a member of Central London Humanists (no cost)</span>
                    </label>
                </div>
                <BR>
                <p class="">If you would like to vote at our AGM or become a committee member you will also need to be a member of <a href="https://humanism.org.uk/join/" target="_blank" class="text-custom-500">Humanists UK</a>.</p>
                <div class="my-3">
                    <label for="active" class="inline-flex items-center">
                        <input type="checkbox" value="c90bc770f9" name="interest3" id="interest3" class="form-checkbox h-5 w-5 text-custom-600 transition duration-150 ease-in-out mt-1 text-green-600" @if($member['interests']['c90bc770f9'] == true) checked='checked' @endif>
                        <span class="ml-2 font-medium font-bold text-gray-700">I'm a member of Humanists UK</span>
                    </label>
                </div>
            </p>
        </div>

        <div class="border border-gray-300 rounded p-4 mt-5">
            <div class="content__gdpr">
                <p>You can unsubscribe or change your choices at any time by clicking the link in the footer of our emails or using the link below.</p><BR>
            </div>
            <div class="text-sm">
                <p>We use Mailchimp as our marketing platform. By clicking below to subscribe, you acknowledge that your information will be transferred to Mailchimp for processing. Learn more about Mailchimp's privacy practices <a href="https://mailchimp.com/legal/" target="_blank" class="text-custom-500">here.</a></p>
            </div>

            <input type="hidden" name="update" value="1"> 

            <div class="flex flex-wrap overflow-hidden">

              <div class="w-1/2 overflow-hidden sm:w-1/2 md:w-1/2 lg:w-1/2 xl:w-1/2">
                <input type="submit" value="Update" name="subscribe" id="subscribe" class="mt-5 bg-blue-500 hover:bg-blue-700 text-white py-2 px-4 rounded">
              </div>

              <div class="w-1/2 overflow-hidden sm:w-1/2 md:w-1/2 lg:w-1/2 xl:w-1/2 text-right">
               <a href="{{  $member['id'] }}/remove" class="popupdelete"><button class="mt-5 bg-red-500 hover:bg-red-700 text-white py-2 px-4 rounded ">Unsubscribe</button></a>
              </div>

            </div>

            
            


        </div>

    </x-form.open> 
    @endif
  </div>

</div>

@endsection

@section('scripts') 
<script src="https://code.jquery.com/jquery-3.6.0.slim.min.js" integrity="sha256-u7e5khyithlIdTpu22PHhENmPcRdFiHRjhAuHcs05RI=" crossorigin="anonymous"></script>
<script src="//cdn.jsdelivr.net/npm/sweetalert2@11"></script>
<script>
$(document).ready(function() {

    $(document).on("click", ".popupdelete", function(e) {
      e.preventDefault();
      var link = $(this).attr('href');
      Swal.fire({
          title: 'Are you sure?',
          text: "This will remove you from our contact list",
          icon: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Yes, unsubscribe me!'
        }).then((result) => {
          if (result.isConfirmed) {
            window.location.href = link;
          }
        });
    });
});
</script>
@endsection